### ISSUE TITLE
Graal support (native image)

### ISSUE THREAD

**Issue by soberich** [stevenschlansker/jackson-blackbird#2]
Just a label to track support of Graal. Particularly native-image.
There should be of course support from Graal itself first (MH) and probably JDK?

So probably at some point current implementation would be able to be build into native-image as is, but it is also possible that author will decide to workaround before that will naturally occur (as it might take really long time)?

@stevenschlansker what do you think?

**Comment by stevenschlansker** [comment]
Is there a specific problem you're aware of regarding native image support currently?
I read through the documentation and (without having tested it) it sounded like it should work with the code as it exists today.

**Comment by soberich** [comment]
I thought there are issues preventing it to be compiled to native-image. 
https://github.com/oracle/graal/issues/955#issuecomment-502934362
Good to now there aren't.
I will close it then.

**Comment by stevenschlansker** [comment]
I was hoping that we fall under this clause:

> Method handles initialized in a class initializer and then used just to invoke a method or access a field are fully supported. Use cases for that are method handles initialized once to access private memembers.

Of course, testing is appreciated -- did you try it?

**Comment by soberich** [comment]
@stevenschlansker though I still haven't tried this is a part I was talking about. 
```
/**
 * The following substitution replaces the usage of {@code MethodHandle} in {@code Java9ChecksumFactory} with a plain
 * constructor invocation when run under GraalVM. This is necessary because the native image generator does not support method
 * handles.
 */
```

https://github.com/quarkusio/quarkus/commit/68584cbcb3836ee7a9c415a380b113c0a902c700

**Comment by stevenschlansker** [comment]
Hm... well, I suppose there's not much to do but try it and see if it's actually an issue here 😸
